# Generated by Django 3.2.9 on 2021-11-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('bank_address', models.CharField(blank=True, max_length=200)),
                ('IFSC_code', models.CharField(blank=True, max_length=11)),
            ],
            options={
                'ordering': ['bank_name'],
            },
        ),
    ]
